[package]
name = "shoveit"
version = "1.0.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_ecs_ldtk = "0.8.0"
bevy_rapier2d = "0.22"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
codegen-units = 1
